[features]
seeds = false
skip-lint = false
[programs.localnet]
vrf_program = "7dsYrsf7cjdMjZBBVv2DzK17Y2Lh8ie16fe48yG1Sn1t"
cpi_example = "DnRABooercz9a3NrVHo7qjbJwRwQoJ48cLPmdC7dNYEu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/arthurtavares/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
